name: Build CHM Viewer

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows 10 Pro 64-Bit
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Lazarus & FPC
      run: |
        choco install fpc --yes
        choco install lazarus --yes
        
    - name: Compile CHM Library Package
      shell: cmd
      run: |
        set %BASEDIR%=%cd%
        set PATH=%PATH%;C:\lazarus;C:\lazarus\fpc\3.2.2\bin\x86_64-win64
        echo %PATH%
        C:\lazarus\lazbuild.exe "C:\lazarus\components\chmhelp\packages\help\lhelpcontrolpkg.lpk"
        C:\lazarus\lazbuild.exe "%BASEDIR%\src\CEF4Delphi\packages\cef4delphi_Lazarus.lpk
        dir
        
    - name: Compile chmViewer Project
      shell: cmd
      run: |
        set BASEDIR=%cd%
        dir %BASEDIR%
        C:\Lazarus\lazbuild.exe "%BASEDIR%\src\chmViewer.lpi
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: chmViewer-Windows.exe
        path: chmViewer.exe
        
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Install FPC + Lazarus
      run: |
        sudo apt update
        sudo apt install -y fpc lazarus lcl-utils lcl-gtk2
        
    - name: Compile Lazarus project (.lpi)
      shell: bash
      run: |
        export BASEDIR=$(pwd)
        echo "base: $BASEDIR"
        /usr/bin/lazbuild $BASEDIR/src/chmViewer.lpi

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: chmViewer-linux
        path: chmViewer
