name: Build CHM Viewer for Windows and Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows 10 Pro 64-Bit
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Lazarus & FPC
      run: |
        choco install fpc --yes
        choco install lazarus --yes

    - name: Compile Lazarus project (.lpi)
      run: |
        dir
        dir C:\\
        
#      run: "C:\\Lazarus\\lazbuild.exe chmViewer.lpi"
    
#    - name: Upload Windows binary
#      uses: actions/upload-artifact@v4
#      with:
#        name: chmViewer-Windows.exe
#        path: chmViewer.exe
        
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Install FPC + Lazarus
      run: |
        sudo apt update
        sudo apt install -y fpc lazarus lcl-utils lcl-gtk2
        
    - name: Compile Laz
      run: where lazbuild && where fpc && which lazbuild && which fpc
        
#    - name: Compile Lazarus project (.lpi)
#      run: lazbuild chmViewer.lpi
#
#    - name: Upload Linux binary
#      uses: actions/upload-artifact@v4
#      with:
#        name: chmViewer-linux
#        path: chmViewer

