name: Build CHM Viewer

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows 10 Pro 64-Bit
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Install Lazarus & FPC
      run: |
        choco install fpc --yes
        choco install lazarus --yes

    - name: Set PATH
      run: echo "C:\lazarus" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding ascii

    - name: Compile CHM Library Package
      shell: cmd
      run: |
        set BASEDIR=%cd%
        set PATH=%PATH%;C:\lazarus;C:\lazarus\fpc\3.2.2\bin\x86_64-win64
        echo %PATH%
        C:\lazarus\lazbuild.exe "%BASEDIR%\src\DCPcrypt\dcpcrypt_laz.lpk"
        C:\lazarus\lazbuild.exe "C:\tools\lazarus\components\chmhelp\packages\help\lhelpcontrolpkg.lpk"
        C:\lazarus\lazbuild.exe "%BASEDIR%\src\CEF4Delphi\packages\cef4delphi_Lazarus.lpk
        
    - name: Compile chmViewer Project
      shell: cmd
      run: |
        set BASEDIR=%cd%
        dir %BASEDIR%
        C:\tools\lazarus\fpc\3.2.2\bin\x86_64-win64\fpc.exe ^
        -Twin64 ^
        -Px86_64 ^
        -MDelphi ^
        -Scghim ^
        -CX ^
        -O3 ^
        -XX ^
        -WG ^
        -l ^
        -vewnhibq ^
        -Filib\x86_64-win64 ^
        -Fusrc ^
        -Fu%BASEDIR%\src\DCPcrypt ^
        -Fu%BASEDIR%\src\DCPcrypt\Chiphers ^
        -Fu%BASEDIR%\src\DCPcrypt\Hashes ^
        -Fu%BASEDIR%\src\CEF4Delphi\source ^
        -Fu%BASEDIR%\src\packages ^
        -FuC:\lazarus\components\ideintf\units\x86_64-win64\win32 ^
        -FuC:\lazarus\components\lazcontrols\lib\x86_64-win64\win32 ^
        -FuC:\lazarus\lcl\units\x86_64-win64\win32 ^
        -FuC:\lazarus\lcl\units\x86_64-win64 ^
        -FuC:\lazarus\components\freetype\lib\x86_64-win64 ^
        -FuC:\lazarus\components\buildintf\units\x86_64-win64 ^
        -FuC:\lazarus\components\lazutils\lib\x86_64-win64 ^
        -FuC:\lazarus\packager\units\x86_64-win64 ^
        -Fu. ^
        -FUlib\x86_64-win64 ^
        -FE. ^
        -ochmViewer.exe ^
        -dLCL ^
        -dLCLwin32

      #C:\Lazarus\lazbuild.exe "%BASEDIR%\src\chmViewer.lpi
    
    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: chmViewer-Windows.exe
        path: chmViewer.exe
        
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Install FPC + Lazarus
      run: |
        sudo apt update
        sudo apt install -y fpc lazarus lcl-utils lcl-gtk2
        
    - name: Compile Lazarus project (.lpi)
      shell: bash
      run: |
        export BASEDIR=$(pwd)
        echo "base: $BASEDIR"
        /usr/bin/fpc ^
        -Twin64 ^
        -Px86_64 ^
        -MDelphi ^
        -Scghim ^
        -CX ^
        -O3 ^
        -XX ^
        -WG ^
        -l ^
        -vewnhibq ^
        -Filib ^
        -Fusrc ^
        -FuD:\a\chmViewer\chmViewer\src\CEF4Delphi\packages\lib\x86_64-win64 ^
        -FuC:\lazarus\components\ideintf\units\x86_64-win64\win32 ^
        -FuC:\lazarus\components\lazcontrols\lib\x86_64-win64\win32 ^
        -FuC:\lazarus\lcl\units\x86_64-win64\win32 ^
        -FuC:\lazarus\lcl\units\x86_64-win64 ^
        -FuC:\lazarus\components\freetype\lib\x86_64-win64 ^
        -FuC:\lazarus\components\buildintf\units\x86_64-win64 ^
        -FuC:\lazarus\components\lazutils\lib\x86_64-win64 ^
        -FuC:\lazarus\packager\units\x86_64-win64 ^
        -Fu. ^
        -FUlib\x86_64-win64 ^
        -FE. ^
        -ochmViewer.exe ^
        -dLCL ^
        -dLCLwin32

    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: chmViewer-linux
        path: chmViewer
