name: Cache for Windows

on:
  workflow_dispatch:

jobs:
  cache-lazarus:
    runs-on: windows-latest
    steps:
      - name: Prepare Directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "C:\tools" -Force
          
      - name: Installi Lazarus/FPC
        shell: cmd
        run: |
          cd C:\tools
          curl -L -o fpcupdeluxe.exe https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/latest/download/fpcupdeluxe-x86_64-win64.exe
          .\fpcupdeluxe.exe --installdir=C:\tools\lazarus --fpcURL=stable --lazURL=stable

      - name: Cache Install Folder
        uses: actions/cache@v4
        with:
          path: C:\tools\lazarus
          key: lazarus-fpc-${{ runner.os }}-v1
