name: Build CHM Viewer for Windows and Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Lazarus & FPC
      run: |
        choco install fpc --yes
        choco install lazarus --yes
        refreshenv
        
  build-linux:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Install FPC + Lazarus
        run: |
          sudo apt update
          sudo apt install -y fpc lazarus lcl-utils lcl-gtk2
